# Generated by Django 5.0.4 on 2024-04-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de devolucion'),
        ),
    ]
