# Generated by Django 5.0.4 on 2024-04-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_alter_prestamo_fecha_devolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(),
        ),
    ]
